### ISSUE TITLE
Save Image Blob Issue

### ISSUE THREAD

**Issue by VivekIshir** [Azure-Samples/azure-sdk-for-net-storage-blob-upload-download#5]
[HI Anybody there to help me for Blob Image Url saving. I am getting error like authentication issue.

using this piece of code 

   public static async Task AddMessageToQueue(string queueName, string content)
        {
            // Retrieve storage account from connection string.
            CloudStorageAccount storageAccount = 
            CloudStorageAccount.Parse(CloudConfigurationManager.GetSetting("StorageConnectionString"));

            // Create the queue [client.](url)
            CloudQueueClient queueClient = storageAccount.CreateCloudQueueClient();

            // Retrieve a reference to a queue.
            CloudQueue queue = queueClient.GetQueueReference(queueName);

            // Create the queue if it doesn't already exist.
            queue.CreateIfNotExists();

            // Create a message and add it to the queue.
            CloudQueueMessage message = new CloudQueueMessage(content);
            await queue.AddMessageAsync(message);
            return;
        }

        public static CloudBlobContainer GetBlobContainer(string containerName)
        {
            //Parse the connection string and return a reference to the storage account.
            CloudStorageAccount storageAccount = 
            CloudStorageAccount.Parse(CloudConfigurationManager.GetSetting("StorageConnectionString"));

            //Create the blob client object.
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();

            //Get a reference to a container to use for the sample code, and create it if it does not exist.
            return blobClient.GetContainerReference(containerName);
        }

        public static string GetBlobSASUrl(string blobpath)
        {
            //Get a reference to a container to use for the sample code, and create it if it does not exist.
            CloudBlobContainer container = GetBlobContainer("vl2profiles");
            container.CreateIfNotExists();

            return GetBlobSasUri(container, blobpath);
        }

        public static string GetBlobSasUri(CloudBlobContainer container, string blobpath)
        {
            string localFilePath = "file:///C://Users/vshukla//Project//NewVoiceLessons/vl2/vl2.API//VLWebAPI//ImageStorage/Vivek.jpg";
            //Get a reference to a blob within the container.
            CloudBlockBlob blob = container.GetBlockBlobReference(localFilePath);

            //Upload text to the blob. If the blob does not yet exist, it will be created.
            //If the blob does exist, its existing content will be overwritten.
            //string blobContent = "This blob will be accessible to clients via a shared access signature (SAS).";
            //blob.UploadText(blobContent);

            //Set the expiry time and permissions for the blob.
            //In this case, the start time is specified as a few minutes in the past, to mitigate clock skew.
            //The shared access signature will be valid immediately.
            SharedAccessBlobPolicy sasConstraints = new SharedAccessBlobPolicy();
            //sasConstraints.SharedAccessStartTime = DateTimeOffset.Now.AddHours(-48);
            //sasConstraints.SharedAccessExpiryTime = DateTimeOffset.Now.AddHours(48);

            sasConstraints.SharedAccessStartTime = DateTimeOffset.Now.AddDays(-2);
            sasConstraints.SharedAccessExpiryTime = DateTimeOffset.Now.AddDays(2);

            sasConstraints.Permissions = SharedAccessBlobPermissions.Read | SharedAccessBlobPermissions.Write;
           // sasConstraints.Permissions = SharedAccessBlobPermissions.Read;

            //Generate the shared access signature on the blob, setting the constraints directly on the signature.
            string sasBlobToken = blob.GetSharedAccessSignature(sasConstraints);

            //Return the URI string for the container, including the SAS token.
            return blob.Uri + sasBlobToken;
        }

    }
 ](url)

it returning me 

![image](https://user-images.githubusercontent.com/34680272/39433527-b4adbcec-4cb3-11e8-81b7-f0d9fe92a361.png)

**Comment by jongio** [comment]
This should be fixed in the latest version of this sample.  Please reopen if you are able to reproduce.  Thank you
